#!/bin/bash

echo "==================================="
echo "  海青菜品研发平台 - 部署指南"
echo "==================================="
echo ""

echo "📦 方案1：Railway + Vercel 部署（推荐，完全免费）"
echo ""
echo "步骤1：部署后端到Railway"
echo "  1. 访问 https://railway.app 并用GitHub登录"
echo "  2. 点击 'New Project' → 'Deploy from GitHub repo'"
echo "  3. 选择 railway-backend 目录"
echo "  4. 等待部署完成（约2分钟）"
echo "  5. 获得后端地址：https://your-app.up.railway.app"
echo ""

echo "步骤2：部署前端到Vercel"
echo "  1. 访问 https://vercel.com 并用GitHub登录"
echo "  2. 点击 'New Project'"
echo "  3. 选择 vercel-frontend 目录"
echo "  4. 点击 'Deploy'"
echo "  5. 获得前端地址：https://your-app.vercel.app"
echo ""

echo "步骤3：修改API地址"
echo "  在 vercel-frontend/index.html 中找到："
echo "  const API_BASE_URL = 'http://localhost:5000';"
echo "  改为："
echo "  const API_BASE_URL = 'https://your-app.up.railway.app';"
echo ""

echo "==================================="
echo "  方案2：使用Cloudflare Tunnel（最快）"
echo "==================================="
echo ""
echo "步骤："
echo "  1. 安装cloudflared："
echo "     curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared"
echo "     chmod +x cloudflared"
echo ""
echo "  2. 启动隧道："
echo "     ./cloudflared tunnel --url http://localhost:5000"
echo ""
echo "  3. 获得公网地址："
echo "     https://xxxx-xxxx-xxxx.trycloudflare.com"
echo ""

echo "==================================="
echo "  方案3：使用ngrok"
echo "==================================="
echo ""
echo "步骤："
echo "  1. 注册ngrok账号：https://ngrok.com"
echo "  2. 获取authtoken"
echo "  3. 安装ngrok"
echo "  4. 运行：ngrok http 5000"
echo "  5. 获得公网地址：https://xxxx.ngrok.io"
echo ""

echo "✅ 推荐使用方案1（Railway + Vercel），完全免费且稳定！"
